// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1RxZSIhdFvbBh-52L5hlBK_aRO6vDzTo',
    appId: '1:448688579975:web:af86ae7b04eefdd4d11f22',
    messagingSenderId: '448688579975',
    projectId: 'cutin-63475',
    authDomain: 'cutin-63475.firebaseapp.com',
    storageBucket: 'cutin-63475.firebasestorage.app',
    measurementId: 'G-7BSV5WHXCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2w8VzIN09IkqUXhAM5FR8dIorwm_wzwA',
    appId: '1:448688579975:android:06a145af743f4ffcd11f22',
    messagingSenderId: '448688579975',
    projectId: 'cutin-63475',
    storageBucket: 'cutin-63475.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRK1pog7HMqTeJhw60rm2Hv9QPP8MK7TQ',
    appId: '1:448688579975:ios:d27bbdb7bf39416bd11f22',
    messagingSenderId: '448688579975',
    projectId: 'cutin-63475',
    storageBucket: 'cutin-63475.firebasestorage.app',
    iosBundleId: 'com.cut.app',
  );

}